language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_script:
  - npm prune
after_success:
  - /bin/bash .travis/after_success.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
