language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/node_modules/slimerjs/src:$PATH
addons:
  firefox: "50.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "yarn global add sassdoc http-server"
sudo: required
script:
  - sassdoc src/theme -d docs/sassdoc
after_success:
  - /bin/bash .travis/after_success.sh
