name: 'Setup nodejs'
description: 'Setup nodejs'
author: 'Talend'
secrets:
  NPM_TOKEN:
    description: 'The NPM token to use'
runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.tool-versions'
        registry-url: 'https://registry.npmjs.org/'
        scope: '@talend'

    - name: Install yarn
      shell: bash
      run: npm i -g yarn

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
