name: 'Setup nodejs'
description: 'Setup nodejs'
author: 'Talend'
inputs:
  NPM_TOKEN:
    description: 'Token used for GitHub Packages auth (defaults to GITHUB_TOKEN)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache asdf
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: |
          ~/.asdf/
        key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}-v0.18.0
        restore-keys: |
          ${{ runner.os }}-asdf-v0.18.0

    - name: Install asdf & tools
      uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1

    - name: Setup npm registry
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:always-auth=true" >> ~/.npmrc
        if [ -n "${{ inputs.NODE_AUTH_TOKEN }}" ]; then
          echo "//npm.pkg.github.com/:_authToken=${{ inputs.NODE_AUTH_TOKEN }}" >> ~/.npmrc
        fi

    - name: Install yarn
      shell: bash
      run: npm i -g yarn

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@0abc2381e688c4d2832f0665a68a01c6e82f0d6c #v2.3.11
