version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@storybook/*"
      - dependency-name: "@talend/*"
      - dependency-name: "*"
        update-types: [ "version-update:semver-minor" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
