export const INPUT_ERRORS = [
	'INVALID_DATE_FORMAT',
	'INVALID_MONTH',
	'INVALID_DAY',
	'DATETIME_INVALID_FORMAT',
	'TIME_FORMAT_INVALID',
];
export const HOUR_ERRORS = ['INVALID_HOUR'];
export const MINUTES_ERRORS = ['INVALID_MINUTES'];
export const SECONDS_ERRORS = ['INVALID_SECONDS'];
