export default {
	REGISTRY_EXPRESSION_PREFIX: 'expression',
	REGISTRY_COMPONENT_PREFIX: '_.route.component',
	REGISTRY_HOOK_PREFIX: '_.route.hook',
	REGISTRY_ACTION_CREATOR_PREFIX: 'actionCreator',
	SAGA_PREFIX: 'saga',
	DID_MOUNT_SAGA_START: 'DID_MOUNT_SAGA_START',
	WILL_UNMOUNT_SAGA_STOP: 'WILL_UNMOUNT_SAGA_STOP',
	IS_HANDLER: 'on',
	IS_HANDLER_STATIC: 'Dispatch',
	IS_HANDLER_DYNAMIC: 'ActionCreator',
};
