export const TF_MUTATE_VALUE = 'TF_MUTATE_VALUE';
export const TF_VALIDATE_ALL = 'TF_VALIDATE_ALL';
export const TF_VALIDATE_PARTIAL = 'TF_VALIDATE_PARTIAL';
export const TF_CREATE_FORM = 'TF_CREATE_FORM';
export const TF_CHANGE_FORM = 'TF_CHANGE_FORM';
export const TF_REMOVE_FORM = 'TF_REMOVE_FORM';
