export const TF_UPDATE_FORM_DATA = 'TF_UPDATE_FORM_DATA';
export const TF_SET_ALL_ERRORS = 'TF_SET_ALL_ERRORS';
export const TF_SET_PARTIAL_ERROR = 'TF_SET_PARTIAL_ERROR';
export const TF_CREATE_FORM = 'TF_CREATE_FORM';
export const TF_REMOVE_FORM = 'TF_REMOVE_FORM';
export const TF_UPDATE_FORM = 'TF_UPDATE_FORM';
