/*export const ACTION_TYPES = {
	ON_OPEN: '@@SOCKET.ON_OPEN',
	ON_CLOSE: '@@SOCKET.ON_CLOSE',
	ON_ERROR: '@@SOCKET.ON_ERROR',
};*/
export const SOCKET_ON_OPEN = '@@SOCKET.ON_OPEN';
export const SOCKET_ON_CLOSE = '@@SOCKET.ON_CLOSE';
export const SOCKET_ON_ERROR = '@@SOCKET.ON_ERROR';
