import Input from './Input';

import InputCheckbox from './Input.Checkbox';
import InputColor from './Input.Color';
import InputCopy from './Input.Copy';
import InputDate from './Input.Date';
import InputDatetimeLocal from './Input.DatetimeLocal';
import InputEmail from './Input.Email';
import InputFile from './Input.File';
import InputHidden from './Input.Hidden';
import InputMonth from './Input.Month';
import InputNumber from './Input.Number';
import InputPassword from './Input.Password';
import InputRadio from './Input.Radio';
import InputRange from './Input.Range';
import InputSearch from './Input.Search';
import InputSwitch from './Input.Switch';
import InputTel from './Input.Tel';
import InputText from './Input.Text';
import InputTime from './Input.Time';
import InputUrl from './Input.Url';
import InputWeek from './Input.Week';

Input.Checkbox = InputCheckbox;
Input.Color = InputColor;
Input.Copy = InputCopy;
Input.Date = InputDate;
Input.DatetimeLocal = InputDatetimeLocal;
Input.Email = InputEmail;
Input.File = InputFile;
Input.Hidden = InputHidden;
Input.Month = InputMonth;
Input.Number = InputNumber;
Input.Password = InputPassword;
Input.Radio = InputRadio;
Input.Range = InputRange;
Input.Search = InputSearch;
Input.Switch = InputSwitch;
Input.Tel = InputTel;
Input.Text = InputText;
Input.Time = InputTime;
Input.Url = InputUrl;
Input.Week = InputWeek;

export default Input;
