language: node_js
cache:
  directories:
    - node_module
notifications:
  email: false
node_js:
  - '6'
install:
  - npm install
script:
  - npm test
after_success:
  - /bin/bash .travis/after_success.sh
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
