export default {
  multipass: true,
  full: true,
  js2svg: {
    pretty: true,
    indent: '\t'
  },
  plugins: [
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeMetadata',
    'removeEditorsNSData',
    'cleanupAttrs',
    'minifyStyles',
    'convertStyleToAttrs',
    'removeRasterImages',
    'cleanupNumericValues',
    'cleanupListOfValues',
    'convertColors',
    'removeUnknownsAndDefaults',
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'removeViewBox',
    'cleanupEnableBackground',
    'removeEmptyText',
    'convertShapeToPath',
    'moveElemsAttrsToGroup',
    'moveGroupAttrsToElems',
    'collapseGroups',
    'convertTransform',
    'removeEmptyAttrs',
    'mergePaths',
    'removeUnusedNS',
    'sortAttrs',
    'removeTitle',
    'removeDesc',
    'removeDimensions',
    'removeAttrs',
    'removeElementsByAttr',
    'addClassesToSVGElement',
    'removeStyleElement',
    'addAttributesToSVGElement'
  ]
};
