name: Delete PR folder in gh-pages
on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  statuses: write
  checks: write
  pages: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout demo branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          path: demo
          ref: gh-pages

      - name: Delete PR folder
        run: |
          rm -rf ./demo/${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit demo for gh-pages
        uses: actions-js/push@968f4695ca558093eadb24ad83cc5891f47e0cdc #v1.6
        with:
          directory: "./demo"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "doc: cleanup demo"
          branch: gh-pages
