name: Design System visual testing

on:
  workflow_dispatch:
    inputs:
      sha:
        description: The SHA-1 hash referring to the commit to check.
        required: true
      ref:
        description: The head branch associated with the pull request.
        required: true
  pull_request:
    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened
    types: [labeled, synchronize, opened, reopened, ready_for_review]
    branches:
      - master
    paths:
      - "packages/design-tokens/**"
      - "packages/design-system/**"
  push:
    branches:
      - master
    paths:
      - "packages/design-tokens/**"
      - "packages/design-system/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ( !github.event.pull_request.draft || contains(github.event.pull_request.labels.*.name, 'need visual approval') )
    environment: pull_request_unsafe
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org/"
          scope: "@talend"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lock --ignore-scripts

      - name: Build @talend/design-tokens
        run: |
          yarn workspace @talend/design-tokens run build:lib

      - name: Publish PR to DS Chromatic
        if: github.ref != 'refs/heads/master'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: "packages/design-system"
          exitZeroOnChanges: true # Option to prevent the workflow from failing in PR

      - name: Publish Master to DS Chromatic
        if: github.ref == 'refs/heads/master'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: "packages/design-system"
          autoAcceptChanges: true # Option to accept any change for this baseline refresh
